BUILT_MODULE_NAME=shannon
DEST_MODULE_LOCATION=/kernel/drivers/block
PACKAGE_NAME=shannon
PACKAGE_VERSION=3.4.3.1
AUTOINSTALL=no
REMAKE_INITRD=no
MAKE="KERNELVER=$kernelver KERNEL_TREE=$kernel_source_dir make shipped modules"
